apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-replica-config
data:
  replica.json: |
    {
      "_id":"dbrepl",
      "members":[
        {"_id":0,"host":"dgiini-db-0:27017"},
        {"_id":1,"host":"dgiini-db-1:27017"},
        {"_id":2,"host":"dgiini-db-2:27017"}
      ]
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-config
data:
  mongod.conf: |
    events {
      worker_connections  1024;
    }
    http {
      server {
        listen 80;
        location / {
          return 200 "===============================\n\n   This is your helm deploy!   \n\n===============================\n";
        }
      }
    }