---
apiVersion: v1
kind: Secret
metadata:
  name: mongo-credential
  namespace: dgiini
type: Opaque
data:
  username: cm9vdAo=
  password: cGFzc3dvcmQK
---
apiVersion: v1
kind: Secret
metadata:
  name: smtp-password
  namespace: dgiini
type: Opaque
data:
  password: S3ViZXJuZXRlc1JvY2tzIQ==
---
apiVersion: v1
kind: Secret
metadata:
  name: sendgrid-api-key
  namespace: dgiini
type: Opaque
data:
  password: S3ViZXJuZXRlc1JvY2tzIQ==