---
apiVersion: v1
kind: Service
metadata:
  name: dgiini-web-service
  namespace: dgiini
  labels:
    app: dgiini
    environment: development
spec:
  selector:
    app: dgiini-web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: dgiini-apigw-service
  namespace: dgiini
  labels:
    app: dgiini
    environment: development
spec:
  selector:
    app: dgiini-apigw
  ports:
    - protocol: TCP
      port: 443
      targetPort: 443
  type: LoadBalancer
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: auth-service
# spec:
#   selector:
#     app: auth
#   ports:
#     - protocol: TCP
#       port: 80
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: task-service
# spec:
#   selector:
#     app: task
#   ports:
#     - protocol: TCP
#       port: 80
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: msg-service
# spec:
#   selector:
#     app: msg
#   ports:
#     - protocol: TCP
#       port: 80
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: notify-service
# spec:
#   selector:
#     app: notify
#   ports:
#     - protocol: TCP
#       port: 80
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: bill-service
# spec:
#   selector:
#     app: bill-api
#   ports:
#     - protocol: TCP
#       port: 80
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: db-service
# spec:
#   selector:
#     app: mongodb
#   ports:
#     - protocol: TCP
#       port: 27017