{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "helmdeploy.serviceAccountName" . }}
  labels:
{{ include "helmdeploy.labels" . | nindent 4 }}
{{- end -}}
