version: '3.3'
services:

    web:
        image: nginx:1.17.2
        environment:
            - NGINX_HOST=dgiini.com
            - NGINX_PORT=80
        ports:
            - "9000:80"
        volumes:
            - ../../dgiini:/usr/share/nginx/html
            - ../nginx/dgiini.template:/etc/nginx/conf.d/dgiini.template
        container_name: web
        #command: /bin/bash -c "envsubst < /etc/nginx/conf.d/dgiini.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"
        networks:
            - dgnet

    auth_api:
        image: node:12.6.0-stretch
        environment:
            - NODE_ENV=development
            - TASK_API_PORT=80
            - MSG_API_PORT=80
            - AUTH_API_PORT=80
            - DB_HOST=db
            - DB_PORT=27017
            - AUTH_DATABASE=dg_authdb
        volumes:
            - ../../msauth:/usr/src/app
        container_name: auth_api
        command: >
            bash -c "cd /usr/src/app
            && yarn
            && node auth_api"
        networks:
            - dgnet

    task_api:
        image: node:12.6.0-stretch
        environment:
            - NODE_ENV=development
            - TASK_API_PORT=8000
            - MSG_API_PORT=8004
            - AUTH_API_PORT=8008
            - DB_HOST=db
            - DB_PORT=27017
            - TASK_DATABASE=dg_taskdb
        volumes:
            - ../../mstask:/usr/src/app
        container_name: task_api
        command: >
            bash -c "cd /usr/src/app
            && yarn
            && node msg_api"
        networks:
            - dgnet

    msg_api:
        image: node:12.6.0-stretch
        environment:
            - NODE_ENV=development
        volumes:
            - ../../msmsg:/usr/src/app
        container_name: msg_api
        command: >
            bash -c "cd /usr/src/app
            && yarn
            && node msg_api"
        networks:
            - dgnet

    db:
        image: mongo:4.1.13-bionic
        container_name: dgmongo
        networks:
            - dgnet

networks:
    dgnet:
