version: "3.7"
services:
  
    web:
      image: gru:5000/dgiini/web:${DGIINI_VERSION}
      restart: always
      environment:
        - NGINX_HOST=sdpro.dynu.com
        - NGINX_PORT=80
      ports:
        - "9000:443"
      networks:
        - dgiininet
      deploy:
          replicas: 1

    apigw:
      image: gru:5000/dgiini/apigw:${DGIINI_VERSION}
      restart: always
      environment:
        - NODE_ENV=development
        - TASK_API_PORT=80
        - MSG_API_PORT=80
        - AUTH_API_PORT=80
        - NOTIFY_API_PORT=80
        - BILL_API_PORT=80
        - APP_NAME=apigw/apigw
        - APP_VERSION=0.1
      ports:
          - "7000:443"
      networks:
          - dgiininet
      deploy:
          replicas: 1

    auth_api:
      image: gru:5000/dgiini/auth:${DGIINI_VERSION}
      restart: always
      environment:
        - NODE_ENV=development
        - TASK_API_PORT=80
        - MSG_API_PORT=80
        - AUTH_API_PORT=80
        - NOTIFY_API_PORT=80
        - BILL_API_PORT=80
        - DB_HOST=dgiini_db
        - DB_PORT=27017
        - AUTH_DATABASE=dg_authdb
        - APP_NAME=auth_api/microservices
        - APP_VERSION=0.1
        - COR_CLIENT_URL=https://sdpro.dynu.com:9000
      networks:
        - dgiininet
      deploy:
        replicas: 1

    task_api:
      image: gru:5000/dgiini/task:${DGIINI_VERSION}
      restart: always
      environment:
        - NODE_ENV=development
        - TASK_API_PORT=80
        - MSG_API_PORT=80
        - AUTH_API_PORT=80
        - DB_HOST=dgiini_db
        - DB_PORT=27017
        - TASK_DATABASE=dg_taskdb
        - APP_NAME=task_api/microservices
        - APP_VERSION=0.1
        - COR_CLIENT_URL=https://sdpro.dynu.com:9000
      networks:
        - dgiininet
      deploy:
        replicas: 1

    msg_api:
      image: gru:5000/dgiini/msg:${DGIINI_VERSION}
      restart: always
      environment:
        - NODE_ENV=development
        - TASK_API_PORT=80
        - MSG_API_PORT=80
        - AUTH_API_PORT=80
        - NOTIFY_API_PORT=80
        - BILL_API_PORT=80
        - DB_HOST=dgiini_db
        - DB_PORT=27017
        - TASK_DATABASE=dg_msgdb
        - APP_NAME=msg_api/microservices
        - APP_VERSION=0.1
        - COR_CLIENT_URL=https://sdpro.dynu.com:9000
      networks:
        - dgiininet
      deploy:
        replicas: 1

    notify_api:
      image: gru:5000/dgiini/notify:${DGIINI_VERSION}
      restart: always
      environment:
        - NODE_ENV=development
        - TASK_API_PORT=80
        - MSG_API_PORT=80
        - AUTH_API_PORT=80
        - NOTIFY_API_PORT=80
        - BILL_API_PORT=80
        - DB_HOST=dgiini_db
        - DB_PORT=27017
        - TASK_DATABASE=dg_notifydb
        - APP_NAME=notify_api/microservices
        - APP_VERSION=0.1
        - SMTP_PW=cG9ienhxaWZhcHpremZnZgo=
        - SENDGRID_API_KEY=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
        - COR_CLIENT_URL=https://sdpro.dynu.com:9000
      networks:
        - dgiininet
      deploy:
        replicas: 1

    bill_api:
      image: gru:5000/dgiini/bill:${DGIINI_VERSION}
      restart: always
      environment:
        - NODE_ENV=development
        - TASK_API_PORT=80
        - MSG_API_PORT=80
        - AUTH_API_PORT=80
        - NOTIFY_API_PORT=80
        - BILL_API_PORT=80
        - DB_HOST=dgiini_db
        - DB_PORT=27017
        - TASK_DATABASE=dg_msbill
        - APP_NAME=bill_api/microservices
        - APP_VERSION=0.1
        - COR_CLIENT_URL=https://sdpro.dynu.com:9000
      networks:
        - dgiininet
      deploy:
        replicas: 1

    db:
      image: mongo:4.2.3-bionic
      restart: always
      volumes:
        - /home/murpheux/data:/data/db
      ports:
        - "27017:27017"
      networks:
        - dgiininet
      deploy:
        replicas: 1

networks:
  dgiininet:
