version: '3.7'
services:

    web:
        build:
          context: ./deploy/web
          dockerfile: dockerfile
        depends_on:
            - apigw
        environment:
            - NGINX_HOST=sdpro.dynu.com
            - NGINX_PORT=80
        ports:
            - "8443:80"
        container_name: web
        networks:
            - dgiininet

    apigw:
        build:
          context: ./deploy/gw
          dockerfile: dockerfile
        depends_on:
            - auth_api
            - task_api
            - msg_api
            - notify_api
            - bill_api
        environment:
            - NODE_ENV=development
            - TASK_API_PORT=80
            - MSG_API_PORT=80
            - AUTH_API_PORT=80
            - APP_NAME=apigw/apigw
            - APP_VERSION=v0.1
            - APP_BUILD=0.0.1.00237
        ports:
            - "8800:443"
        container_name: apigw
        networks:
            - dgiininet

    auth_api:
        build:
          context: ./deploy/auth
          dockerfile: dockerfile
        depends_on:
            - db
        environment:
            - NODE_ENV=development
            - TASK_API_PORT=80
            - MSG_API_PORT=80
            - AUTH_API_PORT=80
            - NOTIFY_API_PORT=80
            - BILL_API_PORT=80
            - REVIEW_API_PORT=80
            - DB_HOST=db
            - DB_PORT=27017
            - AUTH_DATABASE=dg_authdb
            - APP_NAME=auth_api/microservices
            - APP_VERSION=v0.1
            - APP_BUILD=0.0.1.00237
            - COR_CLIENT_URL=https://sdpro.dynu.com:8443
            - GOOGLE_API=https://maps.googleapis.com/maps/api
            - API_KEY=AIzaSyB4rkOg7uSupskMTi-2kiteuvn2KaBswZU
        container_name: auth_api
        networks:
            - dgiininet

    task_api:
        build:
          context: ./deploy/task
          dockerfile: dockerfile
        depends_on:
            - db
        environment:
            - NODE_ENV=development
            - TASK_API_PORT=80
            - MSG_API_PORT=80
            - AUTH_API_PORT=80
            - NOTIFY_API_PORT=80
            - BILL_API_PORT=80
            - REVIEW_API_PORT=80
            - DB_HOST=db
            - DB_PORT=27017
            - TASK_DATABASE=dg_taskdb
            - APP_NAME=task_api/microservices
            - APP_VERSION=v0.1
            - APP_BUILD=0.0.1.00237
            - COR_CLIENT_URL=https://sdpro.dynu.com:8443
        container_name: task_api
        networks:
            - dgiininet

    # msg_api:
    #     build:
    #       context: ./deploy/msg
    #       dockerfile: dockerfile
    #     depends_on:
    #         - db
    #     environment:
    #         - NODE_ENV=development
    #         - TASK_API_PORT=80
    #         - MSG_API_PORT=80
    #         - AUTH_API_PORT=80
    #         - NOTIFY_API_PORT=80
    #         - BILL_API_PORT=80
    #         - REVIEW_API_PORT=80
    #         - DB_HOST=db
    #         - DB_PORT=27017
    #         - TASK_DATABASE=dg_msgdb
    #         - APP_NAME=msg_api/microservices
    #         - APP_VERSION=v0.1
    #         - APP_BUILD=0.0.1.00237
    #         - COR_CLIENT_URL=https://sdpro.dynu.com:8443
    #     container_name: msg_api
    #     networks:
    #         - dgiininet

    notify_api:
        build:
          context: ./deploy/notify
          dockerfile: dockerfile
        depends_on:
            - db
        environment:
            - NODE_ENV=development
            - TASK_API_PORT=80
            - MSG_API_PORT=80
            - AUTH_API_PORT=80
            - NOTIFY_API_PORT=80
            - BILL_API_PORT=80
            - REVIEW_API_PORT=80
            - DB_HOST=db
            - DB_PORT=27017
            - TASK_DATABASE=dg_notifydb
            - APP_NAME=notify_api/microservices
            - APP_VERSION=v0.1
            - APP_BUILD=0.0.1.00237
            - SMTP_PW=cG9ienhxaWZhcHpremZnZgo=
            - SENDGRID_API_KEY=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
            - COR_CLIENT_URL=https://sdpro.dynu.com:8443
        container_name: notify_api
        networks:
            - dgiininet

    # bill_api:
    #     build:
    #       context: ./deploy/bill
    #       dockerfile: dockerfile
    #     depends_on:
    #         - db
    #     environment:
    #         - NODE_ENV=development
    #         - TASK_API_PORT=80
    #         - MSG_API_PORT=80
    #         - AUTH_API_PORT=80
    #         - NOTIFY_API_PORT=80
    #         - BILL_API_PORT=80
    #         - REVIEW_API_PORT=80
    #         - DB_HOST=db
    #         - DB_PORT=27017
    #         - TASK_DATABASE=dg_msbill
    #         - APP_NAME=bill_api/microservices
    #         - APP_VERSION=v0.1
    #         - APP_BUILD=0.0.1.00237
    #         - COR_CLIENT_URL=https://sdpro.dynu.com:8443
    #     container_name: bill_api
    #     networks:
    #         - dgiininet

    review_api:
        build:
          context: ./deploy/review
          dockerfile: dockerfile
        depends_on:
            - db
        environment:
            - NODE_ENV=development
            - TASK_API_PORT=80
            - MSG_API_PORT=80
            - AUTH_API_PORT=80
            - NOTIFY_API_PORT=80
            - BILL_API_PORT=80
            - REVIEW_API_PORT=80
            - DB_HOST=db
            - DB_PORT=27017
            - REVIEW_DATABASE=dg_msreview
            - APP_NAME=review_api/microservices
            - APP_VERSION=v0.1
            - APP_BUILD=0.0.1.00237
            - COR_CLIENT_URL=https://sdpro.dynu.com:8443
        container_name: review_api
        networks:
            - dgiininet

    db:
        image: mongo:4.2.3-bionic
        container_name: dgmongo
        volumes:
          - /home/murpheux/data/mongo:/data/db
        networks:
            - dgiininet

networks:
    dgiininet:
