version: "3.7"
services:

    web:
        image: nginx:1.17.1
        ports:
            - "9000:80"
        volumes:
            - ../../web:/var/www/html
        networks:
            - dgiininet
        deploy:
            replicas: 1

    msg_api:
        image: node:12.6.0-stretch
        environment:
            - NODE_ENV=development
            - TASK_API_PORT=8000
            - MSG_API_PORT=8004
            - AUTH_API_PORT=8008
            - DB_HOST=scarlet
            - DB_PORT=27017
        volumes:
            - ../../msmsg:/usr/src/app
        command: >
            bash -c "cd /usr/src/app
            && yarn api_dev
        networks:
            - dgiininet
        deploy:
            replicas: 1

    auth_api:
        image: node:12.6.0-stretch
        environment:
            - NODE_ENV=development
            - TASK_API_PORT=8000
            - MSG_API_PORT=8004
            - AUTH_API_PORT=8008
            - DB_HOST=scarlet
            - DB_PORT=27017
        volumes:
            - ../../service:/usr/src/app
        command: >
            bash -c "cd /usr/src/app
            && yarn api_dev
        networks:
            - dgiininet
        deploy:
            replicas: 1

    task_api:
        image: node:12.6.0-stretch
        environment:
            - NODE_ENV=development
            - TASK_API_PORT=8000
            - MSG_API_PORT=8004
            - AUTH_API_PORT=8008
            - DB_HOST=scarlet
            - DB_PORT=27017
        volumes:
            - ../../service:/usr/src/app
        command: >
            bash -c "cd /usr/src/app
            && yarn api_dev
        networks:
            - dgiininet
        deploy:
            replicas: 1

    db:
        image: mongo:4.1.13-bionic
        ports:
            - "27018:27017"
        networks:
            - dgiininet
        deploy:
            replicas: 1

networks:
    dgiininet:
