version: '3.7'
services:

    web:
        image: nginx:1.17.1
        environment:
            - NODE_ENV=development
        ports:
            - "9000:80"
        volumes:
            - ../../webui:/var/www/html
        container_name: dgiini_web
        networks:
            - dgnet

    auth_api:
        image: node:12.6.0-stretch
        environment:
            - NODE_ENV=development
        ports:
            - "7000:7000"
        volumes:
            - ../../service:/usr/src/app
        container_name: qt_auth
        command: >
            bash -c "cd /usr/src/app
            && yarn api_dev
        networks:
            - dgnet

    task_api:
        image: node:12.6.0-stretch
        environment:
            - NODE_ENV=development
        ports:
            - "7000:7000"
        volumes:
            - ../../service:/usr/src/app
        container_name: qt_task
        command: >
            bash -c "cd /usr/src/app
            && yarn api_dev
        networks:
            - dgnet

    msg_api:
        image: node:12.6.0-stretch
        environment:
            - NODE_ENV=development
        ports:
            - "7000:7000"
        volumes:
            - ../../service:/usr/src/app
        container_name: qt_task
        command: >
            bash -c "cd /usr/src/app
            && yarn api_dev
        networks:
            - dgnet

    db:
        image: mongo:4.1.13-bionic
        ports:
            - "27018:27017"
        container_name: qmongo
        networks:
            - dgnet

networks:
    dgnet:
