version: "3.7"
services:
  
    web:
      image: murpheux/dgiini_dk_web:${DGIINI_VERSION}
      environment:
        - NGINX_HOST=sdpro.dynu.com
        - NGINX_PORT=80
      ports:
        - "8443:443"
      networks:
        - dgiininet
      deploy:
          replicas: 1

    apigw:
      image: murpheux/dgiini_dk_apigw:${DGIINI_VERSION}
      environment:
        - NODE_ENV=development
        - TASK_API_PORT=80
        - MSG_API_PORT=80
        - AUTH_API_PORT=80
        - NOTIFY_API_PORT=80
        - BILL_API_PORT=80
        - APP_NAME=apigw/apigw
        - APP_VERSION=0.${DGIINI_VERSION}
      ports:
          - "8800:443"
      networks:
          - dgiininet
      deploy:
          replicas: 1

    auth_api:
      image: murpheux/dgiini_dk_auth:${DGIINI_VERSION}
      environment:
        - NODE_ENV=development
        - TASK_API_PORT=80
        - MSG_API_PORT=80
        - AUTH_API_PORT=80
        - NOTIFY_API_PORT=80
        - BILL_API_PORT=80
        - REVIEW_API_PORT=80
        - DB_HOST=dgiini_db
        - DB_PORT=27017
        - AUTH_DATABASE=dg_authdb
        - APP_NAME=auth_api/microservices
        - APP_VERSION=0.${DGIINI_VERSION}
        - COR_CLIENT_URL=https://sdpro.dynu.com:8443
        - GOOGLE_API=https://maps.googleapis.com/maps/api
        - API_KEY=AIzaSyB4rkOg7uSupskMTi-2kiteuvn2KaBswZU
      networks:
        - dgiininet
      deploy:
        replicas: 1

    task_api:
      image: murpheux/dgiini_dk_task:${DGIINI_VERSION}
      environment:
        - NODE_ENV=development
        - TASK_API_PORT=80
        - MSG_API_PORT=80
        - AUTH_API_PORT=80
        - NOTIFY_API_PORT=80
        - BILL_API_PORT=80
        - REVIEW_API_PORT=80
        - DB_HOST=dgiini_db
        - DB_PORT=27017
        - TASK_DATABASE=dg_taskdb
        - APP_NAME=task_api/microservices
        - APP_VERSION=0.${DGIINI_VERSION}
        - COR_CLIENT_URL=https://sdpro.dynu.com:8443
      networks:
        - dgiininet
      deploy:
        replicas: 1

    # msg_api:
    #   image: murpheux/dgiini_dk_msg:${DGIINI_VERSION}
    #   environment:
    #     - NODE_ENV=development
    #     - TASK_API_PORT=80
    #     - MSG_API_PORT=80
    #     - AUTH_API_PORT=80
    #     - NOTIFY_API_PORT=80
    #     - BILL_API_PORT=80
    #     - REVIEW_API_PORT=80
    #     - DB_HOST=dgiini_db
    #     - DB_PORT=27017
    #     - MSG_DATABASE=dg_msgdb
    #     - APP_NAME=msg_api/microservices
    #     - APP_VERSION=0.${DGIINI_VERSION}
    #     - COR_CLIENT_URL=https://sdpro.dynu.com:8443
    #   networks:
    #     - dgiininet
    #   deploy:
    #     replicas: 1

    notify_api:
      image: murpheux/dgiini_dk_notify:${DGIINI_VERSION}
      environment:
        - NODE_ENV=development
        - TASK_API_PORT=80
        - MSG_API_PORT=80
        - AUTH_API_PORT=80
        - NOTIFY_API_PORT=80
        - BILL_API_PORT=80
        - REVIEW_API_PORT=80
        - DB_HOST=dgiini_db
        - DB_PORT=27017
        - NOTIFY_DATABASE=dg_notifydb
        - APP_NAME=notify_api/microservices
        - APP_VERSION=0.${DGIINI_VERSION}
        - SMTP_PW=cG9ienhxaWZhcHpremZnZgo=
        - SENDGRID_API_KEY=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
        - COR_CLIENT_URL=https://sdpro.dynu.com:8443
      networks:
        - dgiininet
      deploy:
        replicas: 1

    # bill_api:
    #   image: murpheux/dgiini_dk_bill:${DGIINI_VERSION}
    #   environment:
    #     - NODE_ENV=development
    #     - TASK_API_PORT=80
    #     - MSG_API_PORT=80
    #     - AUTH_API_PORT=80
    #     - NOTIFY_API_PORT=80
    #     - BILL_API_PORT=80
    #     - REVIEW_API_PORT=80
    #     - DB_HOST=dgiini_db
    #     - DB_PORT=27017
    #     - BILL_DATABASE=dg_msbill
    #     - APP_NAME=bill_api/microservices
    #     - APP_VERSION=0.${DGIINI_VERSION}
    #     - COR_CLIENT_URL=https://sdpro.dynu.com:8443
    #   networks:
    #     - dgiininet
    #   deploy:
    #     replicas: 1

    review_api:
      image: murpheux/dgiini_dk_review:${DGIINI_VERSION}
      environment:
        - NODE_ENV=development
        - TASK_API_PORT=80
        - MSG_API_PORT=80
        - AUTH_API_PORT=80
        - NOTIFY_API_PORT=80
        - BILL_API_PORT=80
        - REVIEW_API_PORT=80
        - DB_HOST=dgiini_db
        - DB_PORT=27017
        - REVIEW_DATABASE=dg_msreview
        - APP_NAME=review_api/microservices
        - APP_VERSION=0.${DGIINI_VERSION}
        - COR_CLIENT_URL=https://sdpro.dynu.com:8443
      networks:
        - dgiininet
      deploy:
        replicas: 1

    db:
      image: mongo:4.2.3-bionic
      volumes:
        - /home/murpheux/data:/data/db
      ports:
        - "27017:27017"
      networks:
        - dgiininet
      deploy:
        replicas: 1

networks:
  dgiininet:
