version: "3.4"
services:

    web:
        image: php:7.0-apache
        environment:
            - NODE_ENV=development
        ports:
            - "9000:80"
        volumes:
            - ../../webui:/var/www/html
        networks:
            - webnet
        deploy:
            replicas: 4

networks:
    webnet:




