https:
  port: 7000
  # hostname: 10.10.2.7
  tls:
    "default":
        key: cert/dgiini.key.pem
        cert: cert/dgiini.cert.pem
admin:
  port: 9876
  # host: 10.10.2.7
apiEndpoints:
  taskApiDefault:
    # host: 10.10.2.7
    paths: '/api/task/v1/'
    methods: GET
  taskApi:
    # host: 10.10.2.7
    paths: '/api/task/v1/*'
  authApiDefault:
    # host: 10.10.2.7
    paths: '/api/auth/v1/'
    methods: GET
  authApi:
    # host: 10.10.2.7
    paths: '/api/auth/v1/*'
  msgApiDefault:
    # host: 10.10.2.7
    paths: '/api/msg/v1/'
    methods: GET
  msgApi:
    # host: 10.10.2.7
    paths: '/api/msg/v1/*'
serviceEndpoints:
  taskService:
    url: 'http://localhost:8000'
  authService:
    url: 'http://localhost:8008'
  msgService:
    url: 'http://localhost:8004'
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - jwt
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  taskDefaultPipeline:
    apiEndpoints:
      - taskApiDefault
    policies:
      - rate-limit:
        - action:
            max: 10
            windowsMs: 120000
            rateLimitBy: '${req.hostname}'
      - proxy:
        - action:
            serviceEndpoint: taskService
            changeOrigin: true
  taskPipeline:
    apiEndpoints:
      - taskApi
    policies:
      # - log:
      #   - action:
      #       message: ${req.ip} - ${req.method} ${req.originalUrl}
      # - jwt:
      #   - action:
      #       secretOrPublicKeyFile: './cert/gen.cert.pem'
      - proxy:
        - action:
            serviceEndpoint: taskService
            changeOrigin: true
  authDefaultPipeline:
    apiEndpoints:
      - authApiDefault
    policies:
      - rate-limit:
        - action:
            max: 10
            windowsMs: 120000
            rateLimitBy: '${req.hostname}'
      - proxy:
        - action:
            serviceEndpoint: authService
            changeOrigin: true
  authPipeline:
    apiEndpoints:
      - authApi
    policies:
      - proxy:
        - action:
            serviceEndpoint: authService
  msgDefaultPipeline:
    apiEndpoints:
      - msgApiDefault
    policies:
      - rate-limit:
        - action:
            max: 10
            windowsMs: 120000
            rateLimitBy: '${req.hostname}'
      - proxy:
        - action:
            serviceEndpoint: msgService
            changeOrigin: true
  msgPipeline:
    apiEndpoints:
      - msgApi
    policies:
      - proxy:
        - action:
            serviceEndpoint: msgService