http:
  port: 7000
admin:
  port: 9876
  host: localhost
apiEndpoints:
  api:
    host: 'localhost'
    paths: '/api'
serviceEndpoints:
  taskService:
    url: 'http://localhost:8000'
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  - name: tkPipeline
    apiEndpoints:
      - api
    policies:
      - proxy:
        - action:
            serviceEndpoint: taskService
            changeOrigin: true