https:
  port: 7000
  tls:
    "default":
        key: cert/dgiini.key.pem
        cert: cert/dgiini.cert.pem
admin:
  port: 9876
apiEndpoints:
  taskApiDefault:
    paths: '/api/task/v1/'
    methods: GET
  taskApi:
    paths: '/api/task/v1/*'
  authApiDefault:
    paths: '/api/auth/v1/'
    methods: GET
  authApi:
    paths: '/api/auth/v1/*'
  msgApiDefault:
    paths: '/api/msg/v1/'
    methods: GET
  msgApi:
    paths: '/api/msg/v1/*'

serviceEndpoints:
  taskService:
    url: 'http://localhost:8000'
  authService:
    url: 'http://localhost:8008'
  msgService:
    url: 'http://localhost:8004'
  notifyService:
    url: 'http://localhost:8002'

policies:
  - cors
  - proxy

pipelines:
  taskDefaultPipeline:
    apiEndpoints:
      - taskApiDefault
    policies:
      - 
        cors:
        - 
          action:
            origin: ['http://sdpro.dynu.com:9000', 'http://sclet:9000']
            methods: 'HEAD,PUT,PATCH,POST,DELETE,OPTIONS'
            allowedHeaders: 'Origin,X-Requested-With,contentType,Content-Type,Accept,Authorization'
            preflightContinue: true
            optionsSuccessStatus: 204
            credentials: true
            maxAge: 600
      - proxy:
        - action:
            serviceEndpoint: taskService
            changeOrigin: true
  taskPipeline:
    apiEndpoints:
      - taskApi
    policies:
      - 
        cors:
        - 
          action:
            origin: ['http://sdpro.dynu.com:9000', 'http://sclet:9000']
            methods: 'HEAD,PUT,PATCH,POST,DELETE,OPTIONS'
            allowedHeaders: 'Origin,X-Requested-With,contentType,Content-Type,Accept,Authorization'
            preflightContinue: true
            optionsSuccessStatus: 204
            credentials: true
            maxAge: 600
      - proxy:
        - action:
            serviceEndpoint: taskService
            changeOrigin: true
  authDefaultPipeline:
    apiEndpoints:
      - authApiDefault
    policies:
      - 
        cors:
        - 
          action:
            origin: ['http://sdpro.dynu.com:9000', 'http://sclet:9000']
            methods: 'HEAD,PUT,PATCH,POST,DELETE,OPTIONS'
            allowedHeaders: 'Origin,X-Requested-With,contentType,Content-Type,Accept,Authorization'
            preflightContinue: true
            optionsSuccessStatus: 204
            credentials: true
            maxAge: 600
      - proxy:
        - action:
            serviceEndpoint: authService
            changeOrigin: true
      
  authPipeline:
    apiEndpoints:
      - authApi
    policies:
      - 
        cors:
        - 
          action:
            origin: ['http://sdpro.dynu.com:9000', 'http://sclet:9000']
            methods: 'HEAD,PUT,PATCH,POST,DELETE,OPTIONS'
            allowedHeaders: 'Origin,X-Requested-With,contentType,Content-Type,Accept,Authorization'
            preflightContinue: true
            optionsSuccessStatus: 204
            credentials: true
            maxAge: 600
      - proxy:
        - action:
            serviceEndpoint: authService
  msgDefaultPipeline:
    apiEndpoints:
      - msgApiDefault
    policies:
      - 
        cors:
        - 
          action:
            origin: ['http://sdpro.dynu.com:9000', 'http://sclet:9000']
            methods: 'HEAD,PUT,PATCH,POST,DELETE,OPTIONS'
            allowedHeaders: 'Origin,X-Requested-With,contentType,Content-Type,Accept,Authorization'
            preflightContinue: true
            optionsSuccessStatus: 204
            credentials: true
            maxAge: 600
      - proxy:
        - action:
            serviceEndpoint: msgService
            changeOrigin: true
  msgPipeline:
    apiEndpoints:
      - msgApi
    policies:
      - 
        cors:
        - 
          action:
            origin: ['http://sdpro.dynu.com:9000', 'http://sclet:9000']
            methods: 'HEAD,PUT,PATCH,POST,DELETE,OPTIONS'
            allowedHeaders: 'Origin,X-Requested-With,contentType,Content-Type,Accept,Authorization'
            preflightContinue: true
            optionsSuccessStatus: 204
            credentials: true
            maxAge: 600
      - proxy:
        - action:
            serviceEndpoint: msgService