https:
  port: 443
  tls:
    "default":
        key: cert/dgiini.key.pem
        cert: cert/dgiini.cert.pem
admin:
  port: 9876
apiEndpoints:
  taskApiDefault:
    paths: '/api/task/v1/'
    methods: GET
  taskApi:
    paths: '/api/task/v1/*'
  authApiDefault:
    paths: '/api/auth/v1/'
    methods: GET
  authApi:
    paths: '/api/auth/v1/*'
  msgApiDefault:
    paths: '/api/msg/v1/'
    methods: GET
  msgApi:
    paths: '/api/msg/v1/*'
serviceEndpoints:
  taskService:
    url: 'http://task_api'
  authService:
    url: 'http://auth_api'
  msgService:
    url: 'http://msg_api'
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - jwt
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  taskDefaultPipeline:
    apiEndpoints:
      - taskApiDefault
    policies:
      - rate-limit:
        - action:
            max: 10
            windowsMs: 120000
            rateLimitBy: '${req.hostname}'
      - proxy:
        - action:
            serviceEndpoint: taskService
            changeOrigin: true
  taskPipeline:
    apiEndpoints:
      - taskApi
    policies:
      # - log:
      #   - action:
      #       message: ${req.ip} - ${req.method} ${req.originalUrl}
      # - jwt:
      #   - action:
      #       secretOrPublicKeyFile: './cert/gen.cert.pem'
      - cors:
        - action:
              origin: '*'
              methods: 'GET,HEAD,PUT,PATCH,POST,DELETE'
              allowedHeaders: '*'
      - proxy:
        - action:
            serviceEndpoint: taskService
            changeOrigin: true
  authDefaultPipeline:
    apiEndpoints:
      - authApiDefault
    policies:
      - rate-limit:
        - action:
            max: 10
            windowsMs: 120000
            rateLimitBy: '${req.hostname}'
      - proxy:
        - action:
            serviceEndpoint: authService
            changeOrigin: true
  authPipeline:
    apiEndpoints:
      - authApi
    policies:
      - cors:
        - action:
              origin: '*'
              methods: 'GET,HEAD,PUT,PATCH,POST,DELETE'
              allowedHeaders: '*'
      - proxy:
        - action:
            serviceEndpoint: authService
  msgDefaultPipeline:
    apiEndpoints:
      - msgApiDefault
    policies:
      - rate-limit:
        - action:
            max: 10
            windowsMs: 120000
            rateLimitBy: '${req.hostname}'
      - proxy:
        - action:
            serviceEndpoint: msgService
            changeOrigin: true
  msgPipeline:
    apiEndpoints:
      - msgApi
    policies:
      - cors:
        - action:
            origin: '*'
            methods: 'GET,HEAD,PUT,PATCH,POST,DELETE'
            allowedHeaders: '*'
      - proxy:
        - action:
            serviceEndpoint: msgService