FROM php:7.0-apache

# Configure ports
# EXPOSE 80 443

# copy configurations
# COPY config/php.ini /usr/local/etc/php/

# copy source code - use volume
#COPY /Users/murpheux/Workspace/Project/seisewa/webui /var/www/html/

# Default environmental variables
#ENV APACHE_DOCUMENT_ROOT /path/to/new/root
