import { NgModule } from "@angular/core";
import { CommonModule } from "@angular/common";
import { MatStepperModule, MatHorizontalStepper } from '@angular/material/stepper';
import {
  MatInputModule,
  MatCheckboxModule,
  MatDatepickerModule,
  MatGridListModule,
  MatNativeDateModule,
  MatAutocompleteModule,
  MatDialogModule,
  MatButtonModule,
  MatIconModule,
  MatToolbarModule,
  MatTooltipModule,
  MatCardModule,
  MatTableModule,
  MatMenuModule,
  MatSlideToggle,
  MatSlideToggleModule,
  MatTabsModule,
  MatDividerModule,
  MatFormFieldModule
} from "@angular/material";
import { DragDropModule } from "@angular/cdk/drag-drop";
import { FormsModule, ReactiveFormsModule } from "@angular/forms";
import { CdkTableModule } from "@angular/cdk/table";
@NgModule({
  declarations: [],
  imports: [
    FormsModule,
    ReactiveFormsModule,
    CommonModule,
    MatStepperModule,
    MatButtonModule,
    MatFormFieldModule,
    MatInputModule,
    MatCheckboxModule,
    MatDatepickerModule,
    MatNativeDateModule,
    MatAutocompleteModule,
    MatDialogModule,
    MatIconModule,
    MatGridListModule,
    MatToolbarModule,
    MatTooltipModule,
    MatButtonModule,
    MatCardModule,
    MatInputModule,
    MatDialogModule,
    MatTableModule,
    MatMenuModule,
    MatIconModule,
    MatDividerModule,
    MatStepperModule,
    CdkTableModule,
    MatSlideToggleModule,
    MatTabsModule,
    DragDropModule
  ],
  exports: [
    FormsModule,
    ReactiveFormsModule,
    MatStepperModule,
    MatButtonModule,
    MatFormFieldModule,
    MatInputModule,
    MatCheckboxModule,
    MatDatepickerModule,
    MatNativeDateModule,
    MatAutocompleteModule,
    MatDialogModule,
    MatIconModule,
    MatGridListModule,
    MatToolbarModule,
    MatTooltipModule,
    MatButtonModule,
    MatCardModule,
    MatInputModule,
    MatDialogModule,
    MatTableModule,
    MatMenuModule,
    MatDividerModule,
    MatStepperModule,
    CdkTableModule,
    MatSlideToggleModule,
    MatTabsModule,
    DragDropModule
  ]
})
export class MaterialDesignModule { }
