---
apiVersion: v1
kind: Secret
metadata:
  name: smtp-password
  namespace: {{ .Values.appName }}
type: Opaque
data:
  password: {{ .Values.smtp.password | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: sendgrid-api-key
  namespace: {{ .Values.appName }}
type: Opaque
data:
  password: {{ .Values.sendgrid.password | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: nginx-cert
  namespace: {{ .Values.appName }}
type: Opaque
data:
  {{- $root := . -}}
  {{- range $path, $bytes := .Files.Glob "cert/ca/dgiini.ca.crt" }}
  {{ base $path }}: {{ $root.Files.Get $path | b64enc }}
  {{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: nginx-key
  namespace: {{ .Values.appName }}
type: Opaque
data:
  {{- $root := . -}}
  {{- range $path, $bytes := .Files.Glob "cert/dgiini.ca.key" }}
  {{ base $path }}: {{ $root.Files.Get $path | b64enc }}
  {{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: dhparam
  namespace: {{ .Values.appName }}
type: Opaque
data:
  {{- $root := . -}}
  {{- range $path, $bytes := .Files.Glob "cert/dhparam.pem" }}
  {{ base $path }}: {{ $root.Files.Get $path | b64enc }}
  {{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: mongo-key
  namespace: {{ .Values.appName }}
type: Opaque
data:
  {{- $root := . -}}
  {{- range $path, $bytes := .Files.Glob "mongo/keyfile.key" }}
  {{ base $path }}: {{ $root.Files.Get $path | b64enc }}
  {{- end }}
