apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-replica-config
  namespace: {{ .Values.appName }}
  labels:
    app: {{ .Values.appName }}
    environment: {{ .Values.environment }}
data:
  replica.json: |
    {
      "_id":"dgiiniRepl",
      "members":[
        {"_id":0,"host":"dgiini-db-0:27017"},
        {"_id":1,"host":"dgiini-db-1:27017"},
        {"_id":2,"host":"dgiini-db-2:27017"}
      ]
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-config
  namespace: {{ .Values.appName }}
  labels:
    app: {{ .Values.appName }}
    environment: {{ .Values.environment }}
data:
  mongod.conf: |
    # mongod.conf

    # for documentation of all options, see:
    #   http://docs.mongodb.org/manual/reference/configuration-options/

    # Where and how to store data.
    storage:
      dbPath: /var/lib/mongodb
      journal:
        enabled: true
    #  engine:
    #  mmapv1:
    #  wiredTiger:

    # where to write logging data.
    systemLog:
      destination: file
      logAppend: true
      path: /var/log/mongodb/mongod.log

    # network interfaces
    net:
      port: 27017
      bindIp: 127.0.0.1


    # how the process runs
    processManagement:
      timeZoneInfo: /usr/share/zoneinfo

    #security:
    setParameter:
        enableLocalhostAuthBypass: false
    security:
        keyFile: /opt/mongo/keyfile.key
        authorization: enabled

    #operationProfiling:

    replication:
      replSetName: dgiiniRepl

    #sharding:

    ## Enterprise-Only Options:

    #auditLog:

    #snmp: