---
apiVersion: v1
kind: Secret
metadata:
  name: mongo-credential
  namespace: {{ .Values.appName }} # Change me or remove if you do not want it
type: Opaque
data:
  mongo-password: Y2hhbmdlbWUK # changeme in base64 encoded 
  MONGO_ROOT_USERNAME: YWRtaW4K
  MONGO_ROOT_PASSWORD: cGFzc3dvcmQK
  MONGO_USERNAME: dHJhaW5pbmcK
  MONGO_PASSWORD: cGFzc3dvcmQK
  MONGO_USERS_LIST: dHJhaW5pbmc6ZGJBZG1pbixyZWFkV3JpdGU6cGFzc3dvcmQK
  username: {{ .Values.auth.db.user | b64enc }}
  password: {{ .Values.auth.db.password | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: smtp-password
  namespace: {{ .Values.appName }}
type: Opaque
data:
  password: {{ .Values.smtp.password | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: sendgrid-api-key
  namespace: {{ .Values.appName }}
type: Opaque
data:
  password: {{ .Values.sendgrid.password | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: nginx-cert
  namespace: {{ .Values.appName }}
type: Opaque
data:
  {{- $root := . -}}
  {{- range $path, $bytes := .Files.Glob "cert/dgiini.com.crt" }}
  {{ base $path }}: {{ $root.Files.Get $path | b64enc }}
  {{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: nginx-key
  namespace: {{ .Values.appName }}
type: Opaque
data:
  {{- $root := . -}}
  {{- range $path, $bytes := .Files.Glob "cert/dgiini.com.key" }}
  {{ base $path }}: {{ $root.Files.Get $path | b64enc }}
  {{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: dhparam
  namespace: {{ .Values.appName }}
type: Opaque
data:
  {{- $root := . -}}
  {{- range $path, $bytes := .Files.Glob "cert/dhparam.pem" }}
  {{ base $path }}: {{ $root.Files.Get $path | b64enc }}
  {{- end }}
