---
apiVersion: v1
kind: Secret
metadata:
  name: mongo-credential
  namespace: {{ .Values.appName }}
type: Opaque
data:
  username: {{ .Values.auth.db.user | b64enc }}
  password: {{ .Values.auth.db.password | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: smtp-password
  namespace: {{ .Values.appName }}
type: Opaque
data:
  password: {{ .Values.smtp.password | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: sendgrid-api-key
  namespace: {{ .Values.appName }}
type: Opaque
data:
  password: {{ .Values.sendgrid.password | b64enc }}