apiVersion: v1
kind: Pod
metadata:
    name: api
spec:
    containers:
        - image: gcr.io/api-app/api_v1
          name: api_v1
          ports:
            - containerPort: 8000
              name: http 
              protocol: TCP