apiVersion: extensions/v1beta1
kind: Deployment
metadata:
    name: stupid-server-deployment
spec:
    replicas: 1
    template:
        metadata:
            labels:
            app: stupid-server
    spec:
      containers:
      - name: stupid-server
        image: <container image>
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
    name: stupid-server
    labels:
        app: stupid-server
spec:
    selector:
        app: stupid-server
    ports:
    - port: 8000
        protocol: TCP
        nodePort: 30061
    type: LoadBalancer
