---
apiVersion: v1
kind: Service
metadata:
  name: dgiini-db-service
  namespace: dgiini
  labels:
    app: dgiini-db
    environment: development
spec:
  selector:
    app: dgiini-db
  ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017
  clusterIP: None
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: dgiini-db
  namespace: dgiini
  labels:
    app: dgiini
    environment: development
spec:
  selector:
    matchLabels:
      app: dgiini-db
  serviceName: dgiini-db
  replicas: 3
  template:
    metadata:
      labels:
        app: dgiini-db
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: mongodb
          image: mongo:4.2.3-bionic
          command:
            - mongod
            - "--replSet"
            - rs0
            - "--smallfiles"
            - "--noprealloc"
          ports:
          - containerPort: 27017
      volumeMounts:
      - name: dgiini-volume
        mountPath: /data/db
      - name: mongo-sidecar
        image: cvallance/mongo-k8s-sidecar
        env:
          - name: MONGO\_SIDECAR\_POD\_LABELS
            value: "role=mongo,environment=test"
  volumeClaimTemplates:
  - metadata:
  name: dgiini-volume
  annotations:
    volume.beta.kubernetes.io/storage-class: "fast"
  spec:
    accessModes: ["ReadWriteOnce"]
    resources:
      requests:
        storage: 1Gi
